package compile

import (
	"sort"
	"strings"
)

// SourcedInstruction pairs a ParsedInstruction with its display-relative
// source path (forward-slash, relative to the project root). RelPath both
// labels the `<!-- Source: ... -->` comment and is the deterministic
// within-group sort key (design.md §4; oracle: template_builder.py:59-60).
type SourcedInstruction struct {
	RelPath string
	ParsedInstruction
}

const globalHeading = "## Global Instructions"

// buildIDPlaceholder is the sentinel line RenderAgentsMD emits in place of
// the real Build ID; StabilizeBuildID replaces it before the content is
// written to disk (oracle: compilation/constants.py BUILD_ID_PLACEHOLDER).
const buildIDPlaceholder = "<!-- Build ID: __BUILD_ID__ -->"

// RenderAgentsMD builds the full single-file AGENTS.md content (still
// containing buildIDPlaceholder -- callers must run StabilizeBuildID before
// writing to disk), mirroring generate_agents_md_template
// (template_builder.py:189-224). version is APM Version's value.
func RenderAgentsMD(instructions []SourcedInstruction, version string) string {
	sections := []string{
		"# AGENTS.md",
		"<!-- Generated by APM CLI from .apm/ primitives -->",
		buildIDPlaceholder,
		"<!-- APM Version: " + version + " -->",
		"",
	}
	if content := renderInstructionsContent(instructions); content != "" {
		sections = append(sections, content)
	}
	sections = append(sections,
		"---",
		"*This file was generated by APM CLI. Do not edit manually.*",
		"*To regenerate: `apm compile`*",
		"",
	)
	return strings.Join(sections, "\n")
}

// renderInstructionsContent mirrors Python's build_conditional_sections +
// render_instructions_block (compilation/template_builder.py:23-84,
// 127-171): global instructions (no applyTo) render first under one
// heading sorted by RelPath, then pattern-scoped groups sorted by pattern
// (the raw applyTo string -- design.md §3, never split on commas), each
// internally sorted by RelPath.
//
// A group's heading is emitted whenever at least one instruction belongs
// to it, even if every instruction in the group has an empty body --
// confirmed oracle quirk (scratch probe 2026-07-11: an isolated
// empty-body instruction still produces an orphan heading with nothing
// under it). Only the per-instruction Source/body/End-source block is
// skipped for an empty body.
func renderInstructionsContent(instructions []SourcedInstruction) string {
	if len(instructions) == 0 {
		return ""
	}

	var globals []SourcedInstruction
	patternGroups := make(map[string][]SourcedInstruction)
	var patterns []string
	for _, inst := range instructions {
		if inst.ApplyTo == "" {
			globals = append(globals, inst)
			continue
		}
		if _, ok := patternGroups[inst.ApplyTo]; !ok {
			patterns = append(patterns, inst.ApplyTo)
		}
		patternGroups[inst.ApplyTo] = append(patternGroups[inst.ApplyTo], inst)
	}
	sort.Strings(patterns)

	var sections []string
	if len(globals) > 0 {
		sections = append(sections, globalHeading, "")
		sections = append(sections, emitGroup(globals)...)
	}
	for _, pattern := range patterns {
		sections = append(sections, "## Files matching `"+pattern+"`", "")
		sections = append(sections, emitGroup(patternGroups[pattern])...)
	}

	return strings.Join(sections, "\n")
}

// emitGroup sorts a group's instructions by RelPath and emits the
// Source/body/End-source block for every non-empty-body member (oracle:
// template_builder.py:70-82, `if instruction.content.strip():`).
func emitGroup(group []SourcedInstruction) []string {
	sorted := make([]SourcedInstruction, len(group))
	copy(sorted, group)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].RelPath < sorted[j].RelPath })

	var lines []string
	for _, inst := range sorted {
		if inst.Body == "" {
			continue
		}
		lines = append(lines,
			"<!-- Source: "+inst.RelPath+" -->",
			inst.Body,
			"<!-- End source: "+inst.RelPath+" -->",
			"",
		)
	}
	return lines
}
