// Randomized zero-false-positive witness for NFR-004 ("known fields, correct
// types -> zero findings") and SC-003, complementing WP01's fixed table-
// driven scenarios in validate_test.go.
//
// Every schema-sourced field's sample values are generated by walking the
// VENDORED SCHEMA itself (schemaTypeSet/schemaArrayItemTypeSet/hasPathPattern,
// defined in validate_schema_sync_test.go), never from r.Kind/r.IsPath --
// generating from the very rule table under test lets a wrong Kind silently
// shrink the input space so it can never expose itself (WP02 finding 2). The
// rule table is still the source of field NAMES and Source classification;
// only the per-field VALUE comes from the schema (or, for docs-sourced
// fields with no schema node, from an explicit hand-written contract case).
package pluginjson

import (
	"encoding/json"
	"fmt"
	"math/rand"
	"strings"
	"testing"
)

// propertyTestExcludedFields are known Source==schema field names this
// generator deliberately never emits, because their mere PRESENCE at the
// top level -- regardless of how correctly they are typed -- always
// produces a warning finding by design (spec.md Edge Cases: 頂層 themes/
// monitors 建議搬移至 experimental 之下; pinned by validate_test.go's own
// EdgeCase-top-level-{themes,monitors}-* subtests, which cover both fields'
// string and array branches AND assert the warning this generator's plain
// zero-findings assertion cannot express). Excluding them here keeps this
// generator honest rather than manufacturing an expected failure.
var propertyTestExcludedFields = map[string]bool{
	"themes":   true,
	"monitors": true,
}

var propertyTestWords = []string{
	"alpha", "beta", "gamma", "widget", "sample", "demo", "item", "thing", "acme", "proto",
}

func propertyTestWord(rnd *rand.Rand) string {
	return propertyTestWords[rnd.Intn(len(propertyTestWords))]
}

// propertyTestKebabName always produces a string that satisfies checkName's
// full chain (non-empty, no space/control/bidi chars, and kebabCaseRe) so a
// generated manifest never trips the Name check.
func propertyTestKebabName(rnd *rand.Rand) string {
	n := 1 + rnd.Intn(3)
	parts := make([]string, n)
	for i := range parts {
		parts[i] = propertyTestWord(rnd)
	}
	return strings.Join(parts, "-")
}

// propertyTestPathString always satisfies pathSyntaxError's three checks
// (not absolute, starts with "./", no ".." segment) -- validate.go's Paths
// check has no file-extension requirement (confirmed by reading
// pathSyntaxError: only those three checks), so no per-field suffix is
// needed here.
func propertyTestPathString(rnd *rand.Rand) string {
	n := 1 + rnd.Intn(3)
	parts := make([]string, n)
	for i := range parts {
		parts[i] = propertyTestWord(rnd)
	}
	return "./" + strings.Join(parts, "/")
}

func propertyTestPathStringArray(rnd *rand.Rand) []any {
	n := 1 + rnd.Intn(3)
	out := make([]any, n)
	for i := range out {
		out[i] = propertyTestPathString(rnd)
	}
	return out
}

// propertyTestDependencyList satisfies checkDependencies/checkDependencyElement
// directly (Validate special-cases "dependencies", bypassing checkKind and
// the vendored schema's own item shape entirely): every element is either a
// bare string or an object carrying a string "name" and, optionally, a
// string "version". This is dependencies' own explicit contract, not a
// schema-derived sample -- checkDependencies enforces "name" is present,
// which a bare schema-shape sample (an empty object) would violate.
func propertyTestDependencyList(rnd *rand.Rand) []any {
	n := rnd.Intn(3)
	out := make([]any, n)
	for i := range out {
		if rnd.Intn(2) == 0 {
			out[i] = propertyTestWord(rnd)
			continue
		}
		dep := map[string]any{"name": propertyTestWord(rnd)}
		if rnd.Intn(2) == 0 {
			dep["version"] = "1.0.0"
		}
		out[i] = dep
	}
	return out
}

// schemaStringSample returns a legal string value: a "./"-prefixed path when
// the schema node this string comes from carries the path pattern, a plain
// word otherwise.
func schemaStringSample(rnd *rand.Rand, isPath bool) string {
	if isPath {
		return propertyTestPathString(rnd)
	}
	return propertyTestWord(rnd)
}

// schemaArrayItemBranchSamples covers every combination an array field's
// declared item-type set (schemaArrayItemTypeSet) permits: a pure-string
// array and/or a pure-object array, plus -- only when the schema commits to
// BOTH -- one array mixing both element kinds together in the same value.
// That mixed sample is the exact shape WP02 finding 1's bug rejected
// (hooks/mcpServers/lspServers' array branch allows a string element
// alongside an object element in the very same array).
func schemaArrayItemBranchSamples(rnd *rand.Rand, itemTypes map[string]bool, isPath bool) []any {
	strItem := func() any { return schemaStringSample(rnd, isPath) }
	objItem := func() any { return map[string]any{} }
	var out []any
	if itemTypes["string"] {
		out = append(out, []any{strItem(), strItem()})
	}
	if itemTypes["object"] {
		out = append(out, []any{objItem(), objItem()})
	}
	if itemTypes["string"] && itemTypes["object"] {
		out = append(out, []any{strItem(), objItem()})
	}
	if len(out) == 0 {
		// No single-type commitment on record -- an empty array is legal
		// for any array-typed field regardless of item shape.
		out = append(out, []any{})
	}
	return out
}

// schemaBranchSamples returns, for a schema-sourced field's property node,
// one representative legal JSON value per top-level shape branch the
// vendored schema declares for it (schemaTypeSet) -- derived from the
// SCHEMA, never from r.Kind/r.IsPath.
func schemaBranchSamples(rnd *rand.Rand, node map[string]any) []any {
	types := schemaTypeSet(node)
	if len(types) == 0 {
		panic(fmt.Sprintf("schemaBranchSamples: schemaTypeSet found no type for node %#v", node))
	}
	isPath := hasPathPattern(node)
	var out []any
	if types["string"] {
		out = append(out, schemaStringSample(rnd, isPath))
	}
	if types["object"] {
		out = append(out, map[string]any{})
	}
	if types["array"] {
		out = append(out, schemaArrayItemBranchSamples(rnd, schemaArrayItemTypeSet(node), isPath)...)
	}
	return out
}

// docsFieldSample returns a legal value for a docs-sourced field (research.
// md R-03: no vendored-schema node exists for these; the Claude Code
// plugins-reference documents their shape instead) -- an explicit,
// hand-written contract case per field, never derived from r.Kind: a
// docs-sourced field has no independent schema to cross-check r.Kind
// against, so at minimum the sample itself must be authored independently
// of it. "experimental" is Source==sourceDocs too but is handled by
// propertyTestExperimentalValue instead (it needs the schema's "themes"/
// "monitors" nodes, not a literal contract case).
func docsFieldSample(rnd *rand.Rand, r rule) any {
	switch r.Name {
	case "displayName":
		return propertyTestWord(rnd)
	case "defaultEnabled":
		return rnd.Intn(2) == 0
	case "metadata":
		return map[string]any{}
	case "workflows":
		if rnd.Intn(2) == 0 {
			return propertyTestPathString(rnd)
		}
		return propertyTestPathStringArray(rnd)
	default:
		panic(fmt.Sprintf("docsFieldSample: no explicit contract case for docs-sourced field %q -- add one rather than falling back to r.Kind", r.Name))
	}
}

// propertyTestExperimentalValue builds a random experimental sub-object.
// experimental.themes and experimental.monitors reuse "themes"'s and
// "monitors"'s own top-level schema anyOf verbatim (validate.go's
// checkExperimentalPathField doc comment; confirmed by direct schema
// inspection), so their samples are derived from those same schema nodes --
// previously this generator always emitted an empty "experimental" object
// and never exercised these sub-fields at all (WP02 finding 2).
func propertyTestExperimentalValue(rnd *rand.Rand, props map[string]any) map[string]any {
	sub := map[string]any{}
	if rnd.Intn(2) == 0 {
		samples := schemaBranchSamples(rnd, props["themes"].(map[string]any))
		sub["themes"] = samples[rnd.Intn(len(samples))]
	}
	if rnd.Intn(2) == 0 {
		samples := schemaBranchSamples(rnd, props["monitors"].(map[string]any))
		sub["monitors"] = samples[rnd.Intn(len(samples))]
	}
	return sub
}

// propertyTestFieldValue returns a legal value for rule r, dispatching by
// name/Source rather than by r.Kind: dependencies and experimental have
// their own dedicated contracts (checkDependencies; themes/monitors reuse),
// every other Source==schema field is sampled from the vendored schema, and
// Source==docs/apm-go fields fall back to an explicit contract case.
func propertyTestFieldValue(rnd *rand.Rand, props map[string]any, r rule) any {
	switch {
	case r.Name == "dependencies":
		return propertyTestDependencyList(rnd)
	case r.Name == "experimental":
		return propertyTestExperimentalValue(rnd, props)
	case r.Source == sourceSchema:
		node, ok := props[r.Name].(map[string]any)
		if !ok {
			panic(fmt.Sprintf("propertyTestFieldValue: rule %q has Source==schema but no schema property node", r.Name))
		}
		samples := schemaBranchSamples(rnd, node)
		return samples[rnd.Intn(len(samples))]
	case r.Source == sourceDocs:
		return docsFieldSample(rnd, r)
	case r.Source == sourceApmGo:
		return map[string]any{}
	default:
		panic(fmt.Sprintf("propertyTestFieldValue: rule %q has unhandled Source %v", r.Name, r.Source))
	}
}

// propertyTestBuildManifest builds one random manifest object: "name" is
// always present and always legal; every other known field (read from the
// live `rules` table, minus propertyTestExcludedFields) is independently
// included about half the time, with a schema- or contract-derived value.
func propertyTestBuildManifest(rnd *rand.Rand, props map[string]any) map[string]any {
	m := map[string]any{"name": propertyTestKebabName(rnd)}
	for _, r := range rules {
		if r.Name == "name" || propertyTestExcludedFields[r.Name] {
			continue
		}
		if rnd.Intn(2) == 0 {
			continue
		}
		m[r.Name] = propertyTestFieldValue(rnd, props, r)
	}
	return m
}

// TestValidate_KnownFieldsCorrectTypes_ZeroFindings is NFR-004/SC-003's
// randomized witness: >=100 independently-seeded manifests, each built only
// from known, correctly-typed fields, must all validate with zero findings.
// Each iteration's RNG is seeded by its own index, so a failure's exact
// manifest is reproducible by re-running that single iteration (not just a
// "test failed" report).
func TestValidate_KnownFieldsCorrectTypes_ZeroFindings(t *testing.T) {
	root := loadSchemaDoc(t)
	props := schemaProperties(t, root)

	const iterations = 200
	for i := 0; i < iterations; i++ {
		rnd := rand.New(rand.NewSource(int64(i)))
		manifest := propertyTestBuildManifest(rnd, props)
		data, err := json.Marshal(manifest)
		if err != nil {
			t.Fatalf("iteration %d: json.Marshal(%+v): %v", i, manifest, err)
		}
		report := Validate(data)
		if len(report.Findings) != 0 {
			t.Fatalf("iteration %d (seed %d): Validate reported %d unexpected finding(s) for a manifest built only from known, correctly-typed fields (NFR-004)\nmanifest: %s\nfindings: %+v",
				i, i, len(report.Findings), data, report.Findings)
		}
	}
}

// TestValidate_EveryPermittedSchemaBranchSampled exhaustively instantiates
// every top-level shape branch -- and every array item-type combination --
// the vendored schema records for each Source==schema field, deterministically
// (not merely with some random probability of eventually rolling it): WP02
// finding 2's demand that every permitted branch of every field get at least
// one sample. "dependencies" is excluded (its own dedicated contract,
// checkDependencies, is exercised directly by validate_test.go's
// dependencies-* scenarios). Top-level "themes"/"monitors" are excluded for
// the same reason as propertyTestExcludedFields above; their branches are
// already pinned, warning included, by validate_test.go's own scenarios.
func TestValidate_EveryPermittedSchemaBranchSampled(t *testing.T) {
	root := loadSchemaDoc(t)
	props := schemaProperties(t, root)
	rnd := rand.New(rand.NewSource(1))

	assertZeroFindings := func(t *testing.T, manifest map[string]any) {
		t.Helper()
		data, err := json.Marshal(manifest)
		if err != nil {
			t.Fatalf("json.Marshal(%+v): %v", manifest, err)
		}
		report := Validate(data)
		if len(report.Findings) != 0 {
			t.Errorf("Validate reported findings for a schema-legal value\nmanifest: %s\nfindings: %+v", data, report.Findings)
		}
	}

	for _, r := range rules {
		if r.Source != sourceSchema || r.Name == "name" || r.Name == "dependencies" || propertyTestExcludedFields[r.Name] {
			continue
		}
		node, ok := props[r.Name].(map[string]any)
		if !ok {
			t.Fatalf("rule %q has Source==schema but no schema property node", r.Name)
		}
		samples := schemaBranchSamples(rnd, node)
		for i, sample := range samples {
			t.Run(fmt.Sprintf("%s/branch%d", r.Name, i), func(t *testing.T) {
				assertZeroFindings(t, map[string]any{"name": "x", r.Name: sample})
			})
		}
	}

	// experimental.themes/experimental.monitors reuse "themes"'/"monitors"'
	// own schema anyOf (see propertyTestExperimentalValue) but can never
	// appear as a literal r.Name, so their branches are pinned here
	// directly instead of through the rules-table loop above.
	for _, sub := range []string{"themes", "monitors"} {
		node := props[sub].(map[string]any)
		samples := schemaBranchSamples(rnd, node)
		for i, sample := range samples {
			t.Run(fmt.Sprintf("experimental.%s/branch%d", sub, i), func(t *testing.T) {
				assertZeroFindings(t, map[string]any{"name": "x", "experimental": map[string]any{sub: sample}})
			})
		}
	}
}
